### ISSUE TITLE
Rosflight Baro measurement calibration

### ISSUE THREAD

**Issue by dallinbriggs** [rosflight/rosflight#20]
This data is pulled from a recent flight of rosflight where two other state estimators were also on-board. As you can see, the measured pressure is different than the other two pressure measurements. The INS and the Pixhawk both use GPS to estimate the barometer bias, but rosflight does not. This means that when you calibrate the altitude at the beginning of the flight, it will indeed set your altitude to zero, but your altitude estimate will not be accurate as you climb in elevation. I observed about a 10 meter altitude difference when the aircraft was at an altitude of 70 meters.
![baro](https://user-images.githubusercontent.com/3312740/28129541-eeb582b6-66f0-11e7-8eb1-0a99f14c911f.jpg)

**Comment by superjax** [comment]
This I believe should be fixed by the new way that the firmware calibrates IMU

**Comment by superjax** [comment]
This was fixed by @len0rd
