### ISSUE TITLE
SIL Error with calibrating IMU

### ISSUE THREAD

**Issue by gellings** [rosflight/rosflight#24]
When calibrating the imu for rosflight_sim fixedwing the autopilot reports an error: _[Autopilot]: Too much movement for IMU cal_  

Any thoughts

**Comment by gellings** [comment]
I just updated to the latest rc1.0 and it seems the error went away but I still can't get it to arm on fixed-wing sil

**Comment by gellings** [comment]
I tried plotting the imu but there seems to be another bug with the imu time-stamp.  The imu does seem to be a little bit wild.  I could be because the aircraft interaction with the ground is weird.  Adding wheels to the vehicle seemed to not make a difference.

**Comment by superjax** [comment]
I fixed the IMU time stamp bug, but I still don't know what is going on with the IMU calibration.  I would try setting the noise to zero and see if it still worked, or trying to print out the max - min vector when the IMU calibration is performed.
