### ISSUE TITLE
Negative Airspeed readings

### ISSUE THREAD

**Issue by dallinbriggs** [rosflight/rosflight#31]
It seems as though the differential pressure sensor can return outliers for the pressure reading. This causes the airspeed to go negative for a second. We should probably do some outlier rejection on this. 
![diff_pres](https://user-images.githubusercontent.com/3312740/28470060-b3e3d122-6df5-11e7-80fb-67219c09ded0.jpg)

**Comment by drinkdhmo** [comment]
We should implement outlier rejection or other filtering at the ROScopter/ROSplane level so that high level applications get raw data from the sensors and can then best decide how to filter it.

**Comment by superjax** [comment]
Does anyone want to implement this?  (It would be best in the sensors.cpp file of the firmware)

**Comment by superjax** [comment]
This was fixed a long time ago!  Thanks @drinkdhmo
