### ISSUE TITLE
GPS topic name

### ISSUE THREAD

**Issue by dallinbriggs** [rosflight/rosflight#44]
Rosflight publishes gps/data and rosplane listens to gps. It's not a big deal to remap every time, but it's annoying. Either rosplane should be switched to listen to gps/data, or rosflight should be switched to publish gps. Is there a reason we should call the topic gps/data rather than gps? I'm happy to switch rosplane to gps/data if that is easiest.

**Comment by gellings** [comment]
I'm pretty sure we settled on gps.  It's not really a rosflight thing because rosflight currently doesn't provide gps (that's the real issue) but I'll fix the dirver in rosflight utils.
