### ISSUE TITLE
Force added as torque in rosflight_sim/src/multirotor_forces_and_moments.cpp

### ISSUE THREAD

**Issue by ttdm** [rosflight/rosflight#62]
Hello, 

In the master branch and the rosflight_sim_pkg branch ( at least ), you find the following lines (170 -175) : 
```
Eigen::Matrix<double, 6,1> forces;
  // Apply other forces (drag) <- follows "Quadrotors and Accelerometers - State Estimation With an Improved Dynamic Model"
  // By Rob Leishman et al.
  forces.block<3,1>(3,0) = -linear_mu_ * Va;
  forces.block<3,1>(3,0) = -angular_mu_ * x.omega + output_forces_and_torques.block<3,1>(0,0);

  // Apply ground effect and thrust
  forces(2) += output_forces_and_torques(3) - ground_effect;

return forces;
```

I believe there is a typo and it should be 
`  forces.block<3,1>(**0,0**) = -linear_mu_ * Va;`

I checked, this is what you have in rosflight_sim_pkg_dan (and the current code makes no sense) so it is very likely to be a typo.

TTDM,

Ps : sorry for not using the tools github offers to do it, I just don't know how to ask for the modification on all the branches that need it.

**Comment by superjax** [comment]
Thank you!

I am so sorry that I missed this one...  You're totally right.
