### ISSUE TITLE
ROS release

### ISSUE THREAD

**Issue by dpkoch** [rosflight/rosflight#8]
Need to figure out how to release this stack through the ROS build farm.

**Comment by dpkoch** [comment]
Also need to remember to bump version tags in all `package.xml` files

**Comment by dpkoch** [comment]
Closed by ros/rosdistro#15049

**Comment by dpkoch** [comment]
That last release failed on the build farm due to some missing dependencies; I think I've fixed that, should be resolved by ros/rosdistro#15054

**Comment by superjax** [comment]
Cool!  So, how does this work?  I understand that you somehow made `rosflight-release` a part of `rosdistro` but how does that make its way to the main repository?

**Comment by dpkoch** [comment]
One more try: ros/rosdistro#15057

@superjax Magic.

So I think once they merge the pull request it triggers a new build on their Jenkins buildfarm server. The buildfarm uses the `rosdistro` configuration file to know which packages to include and what version, so the info we add to that file tells the buildfarm to include our packages. Then every once in a while those built versions get pulled into the debian repository; still not positive how/when that step happens. It's magic.

**Comment by dpkoch** [comment]
See ros/rosdistro#15149

**Comment by dpkoch** [comment]
Closed by ros/rosdistro#15149
