### ISSUE TITLE
How to set parameter?

### ISSUE THREAD

**Issue by Dines97** [rosflight/rosflight#91]
1. Ubuntu
2. master

I want to change the value of the mixer. For this, I use "rosservice call / param_set mixer 1". To which returns: "exists: False". When trying to read this parameter:
exists: False
value: 0.0
So I still do not understand about the value of the mixer. How to define it?

**Comment by dpkoch** [comment]
Hi @Dines97. The parameter name is case-sensitive, so use `rosservice call /param_set MIXER 1`.

I'm not sure if you were asking this, but if you're also wondering where those values are defined they're listed at http://docs.rosflight.org/en/latest/user-guide/hardware-setup/#motor-layouts.

Hope that helps.
